### ISSUE TITLE
Broken after Loxone update to release version 9.0.9.26

### ISSUE THREAD

**Issue by jdstroy70** [alladdin/node-lox-ws-api#11]
Loxone changed their auth scheme: https://www.loxone.com/dede/wp-content/uploads/sites/2/2016/08/0900_Communicating-with-the-Miniserver.pdf

This one is not functional anymore.

**Comment by Nexus2k** [comment]
Duplicate of https://github.com/alladdin/node-lox-ws-api/issues/10
